name = "costar"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:deploy"
[build.upload]
format = "service-worker"
node_version = "20.9.0"

[site]
bucket = ".vercel/output/static"
pages_build_output_dir = ".vercel/output/static"